rc genneration , vehicle module implementation
blackoders/online_registration pull request #4
Opened 2023-02-20 12:36 UTC by singlefleck

2023-02-20 13:09 UTC, blackode requested changes

2023-02-20 13:09 UTC, blackode commented on lib/registration/customer.ex
>    @spec is_valid(%{:aadhar => any, :name => binary, optional(any) => any}) :: nil | true
@spec return type is wrong here... 
change that to boolean

2023-02-20 13:09 UTC, blackode commented on lib/registration/customer.ex
>    @spec is_valid(%{:aadhar => any, :name => binary, optional(any) => any}) :: nil | true
```suggestion
  @spec is_valid(map()) :: boolean()
```

2023-02-20 13:09 UTC, blackode commented on lib/registration/vehice_registration.ex
> +    rc_details = %{name: name, aadhar: aadhar, vehicle_number: vehicle_number, state: state}
```suggestion
    rc_details = %{name: name, aadhar: aadhar, vehicle_number: vehicle_number, state: state}
    rc = rc_template(rc_details)
    IO.puts(rc)
```

2023-02-20 13:09 UTC, blackode commented on lib/static/state_codes.ex
> +  end
```suggestion
```

2023-02-20 13:09 UTC, blackode commented on lib/static/state_codes.ex
> +      "please start from first"
```suggestion
      {1, 5}
```

2023-02-20 13:09 UTC, blackode commented on lib/static/state_codes.ex
> +    code = get_state_code
```suggestion
    code = get_state_code()
```

2023-02-20 13:09 UTC, blackode commented on mix.exs
> +      {:ecto_sql, "~> 3.0"},
```suggestion
       {:ecto, "~> 3.8"}
```

2023-02-20 15:48 UTC, singlefleck commented on mix.exs
> +      {:ecto_sql, "~> 3.0"},
![image](https://user-images.githubusercontent.com/32371403/220150735-76fdb365-27fe-4bf6-85df-63295e17a580.png)

2023-02-21 15:33 UTC, blackode approved these changes

2023-02-21 15:35 UTC, merged